$(document).ready(function() {
    $("#li1").click(function() {
        $(this).css({
            "background-color": "#fa5140",
            color: "#ffffff",
            transition: "0.5s"
        }), $("#li2").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li3").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li4").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li5").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li6").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li7").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li8").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li9").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li10").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#2017").css({
            display: "block",
            transition: "0.5s"
        }), $("#2016").css({
            display: "none",
            transition: "0.5s"
        }), $("#2015").css({
            display: "none",
            transition: "0.5s"
        }), $("#2014").css({
            display: "none",
            transition: "0.5s"
        }), $("#2013").css({
            display: "none",
            transition: "0.5s"
        }), $("#2012").css({
            display: "none",
            transition: "0.5s"
        }), $("#2011").css({
            display: "none",
            transition: "0.5s"
        }), $("#2010").css({
            display: "none",
            transition: "0.5s"
        }), $("#2009").css({
            display: "none",
            transition: "0.5s"
        }), $("#2008").css({
            display: "none",
            transition: "0.5s"
        })
    }), $("#li2").click(function() {
        $("#li1").removeClass("id1"), $(this).css({
            "background-color": "#fa5140",
            color: "#ffffff",
            transition: "0.5s"
        }), $("#li1").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li3").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li4").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li5").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li6").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li7").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li8").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li9").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li10").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#2017").css({
            display: "none",
            transition: "0.5s"
        }), $("#2016").css({
            display: "block",
            transition: "0.5s"
        }), $("#2015").css({
            display: "none",
            transition: "0.5s"
        }), $("#2014").css({
            display: "none",
            transition: "0.5s"
        }), $("#2013").css({
            display: "none",
            transition: "0.5s"
        }), $("#2012").css({
            display: "none",
            transition: "0.5s"
        }), $("#2011").css({
            display: "none",
            transition: "0.5s"
        }), $("#2010").css({
            display: "none",
            transition: "0.5s"
        }), $("#2009").css({
            display: "none",
            transition: "0.5s"
        }), $("#2008").css({
            display: "none",
            transition: "0.5s"
        })
    }), $("#li3").click(function() {
        $("#li1").removeClass("id1"), $(this).css({
            "background-color": "#fa5140",
            color: "#ffffff",
            transition: "0.5s"
        }), $("#li1").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li2").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li4").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li5").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li6").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li7").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li8").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li9").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li10").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#2017").css({
            display: "none",
            transition: "0.5s"
        }), $("#2016").css({
            display: "none",
            transition: "0.5s"
        }), $("#2015").css({
            display: "block",
            transition: "0.5s"
        }), $("#2014").css({
            display: "none",
            transition: "0.5s"
        }), $("#2013").css({
            display: "none",
            transition: "0.5s"
        }), $("#2012").css({
            display: "none",
            transition: "0.5s"
        }), $("#2011").css({
            display: "none",
            transition: "0.5s"
        }), $("#2010").css({
            display: "none",
            transition: "0.5s"
        }), $("#2009").css({
            display: "none",
            transition: "0.5s"
        }), $("#2008").css({
            display: "none",
            transition: "0.5s"
        })
    }), $("#li4").click(function() {
        $("#li1").removeClass("id1"), $(this).css({
            "background-color": "#fa5140",
            color: "#ffffff",
            transition: "0.5s"
        }), $("#li1").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li3").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li2").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li5").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li6").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li7").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li8").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li9").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li10").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#2017").css({
            display: "none",
            transition: "0.5s"
        }), $("#2016").css({
            display: "none",
            transition: "0.5s"
        }), $("#2015").css({
            display: "none",
            transition: "0.5s"
        }), $("#2014").css({
            display: "block",
            transition: "0.5s"
        }), $("#2013").css({
            display: "none",
            transition: "0.5s"
        }), $("#2012").css({
            display: "none",
            transition: "0.5s"
        }), $("#2011").css({
            display: "none",
            transition: "0.5s"
        }), $("#2010").css({
            display: "none",
            transition: "0.5s"
        }), $("#2009").css({
            display: "none",
            transition: "0.5s"
        }), $("#2008").css({
            display: "none",
            transition: "0.5s"
        })
    }), $("#li5").click(function() {
        $("#li1").removeClass("id1"), $(this).css({
            "background-color": "#fa5140",
            color: "#ffffff",
            transition: "0.5s"
        }), $("#li1").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li3").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li4").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li2").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li6").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li7").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li8").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li9").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li10").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#2017").css({
            display: "none",
            transition: "0.5s"
        }), $("#2016").css({
            display: "none",
            transition: "0.5s"
        }), $("#2015").css({
            display: "none",
            transition: "0.5s"
        }), $("#2014").css({
            display: "none",
            transition: "0.5s"
        }), $("#2013").css({
            display: "block",
            transition: "0.5s"
        }), $("#2012").css({
            display: "none",
            transition: "0.5s"
        }), $("#2011").css({
            display: "none",
            transition: "0.5s"
        }), $("#2010").css({
            display: "none",
            transition: "0.5s"
        }), $("#2009").css({
            display: "none",
            transition: "0.5s"
        }), $("#2008").css({
            display: "none",
            transition: "0.5s"
        })
    }), $("#li6").click(function() {
        $("#li1").removeClass("id1"), $(this).css({
            "background-color": "#fa5140",
            color: "#ffffff",
            transition: "0.5s"
        }), $("#li1").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li3").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li4").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li5").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li2").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li7").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li8").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li9").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li10").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#2017").css({
            display: "none",
            transition: "0.5s"
        }), $("#2016").css({
            display: "none",
            transition: "0.5s"
        }), $("#2015").css({
            display: "none",
            transition: "0.5s"
        }), $("#2014").css({
            display: "none",
            transition: "0.5s"
        }), $("#2013").css({
            display: "none",
            transition: "0.5s"
        }), $("#2012").css({
            display: "block",
            transition: "0.5s"
        }), $("#2011").css({
            display: "none",
            transition: "0.5s"
        }), $("#2010").css({
            display: "none",
            transition: "0.5s"
        }), $("#2009").css({
            display: "none",
            transition: "0.5s"
        }), $("#2008").css({
            display: "none",
            transition: "0.5s"
        })
    }), $("#li7").click(function() {
        $("#li1").removeClass("id1"), $(this).css({
            "background-color": "#fa5140",
            color: "#ffffff",
            transition: "0.5s"
        }), $("#li1").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li3").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li4").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li5").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li6").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li2").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li8").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li9").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li10").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#2017").css({
            display: "none",
            transition: "0.5s"
        }), $("#2016").css({
            display: "none",
            transition: "0.5s"
        }), $("#2015").css({
            display: "none",
            transition: "0.5s"
        }), $("#2014").css({
            display: "none",
            transition: "0.5s"
        }), $("#2013").css({
            display: "none",
            transition: "0.5s"
        }), $("#2012").css({
            display: "none",
            transition: "0.5s"
        }), $("#2011").css({
            display: "block",
            transition: "0.5s"
        }), $("#2010").css({
            display: "none",
            transition: "0.5s"
        }), $("#2009").css({
            display: "none",
            transition: "0.5s"
        }), $("#2008").css({
            display: "none",
            transition: "0.5s"
        })
    }), $("#li8").click(function() {
        $("#li1").removeClass("id1"), $(this).css({
            "background-color": "#fa5140",
            color: "#ffffff",
            transition: "0.5s"
        }), $("#li1").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li3").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li4").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li5").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li6").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li7").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li2").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li9").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li10").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#2017").css({
            display: "none",
            transition: "0.5s"
        }), $("#2016").css({
            display: "none",
            transition: "0.5s"
        }), $("#2015").css({
            display: "none",
            transition: "0.5s"
        }), $("#2014").css({
            display: "none",
            transition: "0.5s"
        }), $("#2013").css({
            display: "none",
            transition: "0.5s"
        }), $("#2012").css({
            display: "none",
            transition: "0.5s"
        }), $("#2011").css({
            display: "none",
            transition: "0.5s"
        }), $("#2010").css({
            display: "block",
            transition: "0.5s"
        }), $("#2009").css({
            display: "none",
            transition: "0.5s"
        }), $("#2008").css({
            display: "none",
            transition: "0.5s"
        })
    }), $("#li9").click(function() {
        $("#li1").removeClass("id1"), $(this).css({
            "background-color": "#fa5140",
            color: "#ffffff",
            transition: "0.5s"
        }), $("#li1").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li3").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li4").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li5").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li6").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li7").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li8").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li2").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li10").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#2017").css({
            display: "none",
            transition: "0.5s"
        }), $("#2016").css({
            display: "none",
            transition: "0.5s"
        }), $("#2015").css({
            display: "none",
            transition: "0.5s"
        }), $("#2014").css({
            display: "none",
            transition: "0.5s"
        }), $("#2013").css({
            display: "none",
            transition: "0.5s"
        }), $("#2012").css({
            display: "none",
            transition: "0.5s"
        }), $("#2011").css({
            display: "none",
            transition: "0.5s"
        }), $("#2010").css({
            display: "none",
            transition: "0.5s"
        }), $("#2009").css({
            display: "block",
            transition: "0.5s"
        }), $("#2008").css({
            display: "none",
            transition: "0.5s"
        })
    }), $("#li10").click(function() {
        $("#li1").removeClass("id1"), $(this).css({
            "background-color": "#fa5140",
            color: "#ffffff",
            transition: "0.5s"
        }), $("#li1").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li3").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li4").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li5").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li6").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li7").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li8").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li9").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#li2").css({
            "background-color": "#ffffff",
            color: "#414141",
            transition: "0.5s"
        }), $("#2017").css({
            display: "none",
            transition: "0.5s"
        }), $("#2016").css({
            display: "none",
            transition: "0.5s"
        }), $("#2015").css({
            display: "none",
            transition: "0.5s"
        }), $("#2014").css({
            display: "none",
            transition: "0.5s"
        }), $("#2013").css({
            display: "none",
            transition: "0.5s"
        }), $("#2012").css({
            display: "none",
            transition: "0.5s"
        }), $("#2011").css({
            display: "none",
            transition: "0.5s"
        }), $("#2010").css({
            display: "none",
            transition: "0.5s"
        }), $("#2009").css({
            display: "none",
            transition: "0.5s"
        }), $("#2008").css({
            display: "block",
            transition: "0.5s"
        })
    })
});